from core.globals import LANGUAGE_EN_KEY, LANGUAGE_RU_KEY, GENERATOR_OVERLAY_ABOVE_KEY, GENERATOR_OVERLAY_INSIDE_KEY, LANGUAGE_UZ_KEY

OVERLAY_ABOVE_BUTTON_TEXT = {
    LANGUAGE_EN_KEY: 'Above the photo',
    LANGUAGE_RU_KEY: 'Над фото',
    LANGUAGE_UZ_KEY: 'Fotosurat ustida',
}

OVERLAY_UNDER_BUTTON_TEXT = {
    LANGUAGE_EN_KEY: 'Under the photo',
    LANGUAGE_RU_KEY: 'Под фото',
    LANGUAGE_UZ_KEY: 'Fotosurat ostida',
}

OVERLAY_IN_LANGUAGES = {
    OVERLAY_ABOVE_BUTTON_TEXT[LANGUAGE_EN_KEY]: GENERATOR_OVERLAY_ABOVE_KEY,
    OVERLAY_ABOVE_BUTTON_TEXT[LANGUAGE_RU_KEY]: GENERATOR_OVERLAY_ABOVE_KEY,
    OVERLAY_ABOVE_BUTTON_TEXT[LANGUAGE_UZ_KEY]: GENERATOR_OVERLAY_ABOVE_KEY,
    OVERLAY_UNDER_BUTTON_TEXT[LANGUAGE_EN_KEY]: GENERATOR_OVERLAY_INSIDE_KEY,
    OVERLAY_UNDER_BUTTON_TEXT[LANGUAGE_RU_KEY]: GENERATOR_OVERLAY_INSIDE_KEY,
    OVERLAY_UNDER_BUTTON_TEXT[LANGUAGE_UZ_KEY]: GENERATOR_OVERLAY_INSIDE_KEY,
}
